version: "3.9"

services:
  db:
    image: postgres:15
    container_name: test_database
    env_file: .env.test
    ports: 
      - "5433:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    restart: always


  app:
    build: .
    container_name: test_app
    depends_on: 
      - db
    env_file: .env.test
    command: 
      - sh
      - -c
      - |
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000

    ports: 
      - "8001:8000"
    volumes: 
      - .:/app
    restart: always
volumes:
  pgdata:
