version: "3.9"

services:
  db: 
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi-app
    depends_on:
      - db
    env_file:
      - .env.app
    ports:
      - "8000"
    volumes:
      - .:/app
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

volumes:
  pgdata:
      
