"""add status shipped

Revision ID: 5ab0b713e28c
Revises: 496c071f2cc9
Create Date: 2026-04-02 21:48:05.754047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ab0b713e28c'
down_revision: Union[str, Sequence[str], None] = '496c071f2cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE orderstatus ADD VALUE IF NOT EXISTS 'shipped'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
