name: FastAPI CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build Containers
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml build

      - name: Run tests
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm app pytest -v